# Используем официальный образ Python версии 3.9
FROM python:3.9

# Устанавливаем зависимости для тестирования
RUN pip install pytest

# Копируем файлы из локальной директории в контейнер
COPY . /app

# Задаем рабочую директорию контейнера
WORKDIR /app

# Выполняем команду для запуска тестов при создании контейнера
CMD ["pytest", "tests"]

# docker build . -f Dockerfile -t home_work_image
