# Используем официальный образ Python версии 3.9
FROM python:3.9

# Копируем файлы из локальной директории в контейнер
COPY . /app

# Устанавливаем зависимости для тестирования
RUN pip install pytest
RUN pip install psycopg2

# Задаем рабочую директорию контейнера
WORKDIR /app

# Выполняем команду для запуска тестов при создании контейнера
CMD ["pytest", "-k", "test_db"]

# docker build . -f Dockerfile -t home_work_image
# docker-compose up --build
